apiVersion: v1
kind: Namespace
metadata:
  name: woocommerce-platform
  labels:
    name: woocommerce-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: woocommerce-stores
  labels:
    name: woocommerce-stores