apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-provisioning-worker
  namespace: woocommerce-platform
  labels:
    app: store-worker
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-worker
  template:
    metadata:
      labels:
        app: store-worker
        tier: worker
    spec:
      serviceAccountName: woocommerce-worker-sa
      containers:
      - name: worker
        image: vishwajeet075/store-provision:latest  
        imagePullPolicy: Always
        command: ["npm", "run", "worker"]  
        env:

        - name: NODE_ENV
          value: "production"
        
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        
        - name: HELM_NAMESPACE
          value: "woocommerce-stores"
        - name: BASE_DOMAIN
          value: "stores.example.com"
        - name: INGRESS_CLASS
          value: "nginx"
        - name: STORAGE_CLASS
          value: "hostpath"
        - name: CERT_ISSUER
          value: "letsencrypt-prod"

        - name: DB_NAME
          value: "woocommerce_platform"
        - name: DB_USER
          value: "root"
        - name: DB_HOST
          value: "mysql-service" 
        - name: DB_PORT
          value: "3306"
        
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password

        - name: SHARED_MYSQL_HOST
          value: "mysql-service"  
        - name: SHARED_MYSQL_PORT
          value: "3306"
        - name: SHARED_MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        
      
      restartPolicy: Always