apiVersion: v1
kind: ServiceAccount
metadata:
  name: woocommerce-backend-sa
  namespace: woocommerce-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: woocommerce-worker-sa
  namespace: woocommerce-platform

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: woocommerce-frontend-sa
  namespace: woocommerce-platform