{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "woocommerce-store.fullname" . }}
  labels:
    {{ include "woocommerce-store.labels" . | nindent 4 }}
  {{ with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  {{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "woocommerce-store.fullname" .)) }}
  {{ end }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "woocommerce-store.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{ end }}